name: Compile Tulip Kernel

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tulip-kernel repository
        uses: actions/checkout@v2
        with:
          repository: 'l4feer/tulip-kernel'
          path: 'tulip-kernel'

      - name: Set up Android build environment
        uses: actions/setup-android@v1

      - name: Compile kernel
        run: |
          cd tulip-kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-android-
          export SUBARCH=arm64
          make tulip_defconfig
          make -j$(nproc)
