name: Debug Workflow

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Open shell
        run: |
          sudo apt install clang gcc
          git clone https://github.com/l4feer/tulip-kernel -b feature
          cd tulip-kernel
          make O=out tulip-newcam_defconfig
          make O=out -j$(nproc)
