name: Github Action

on:
  push:
    branches:[ main, wip ]
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Verify Version
        run: flutter --version

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: OS check
        run: uname -a
